[package]
name = "lunul-local-cluster"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lunul-local-cluster"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
lunul-accounts-db = { workspace = true }
lunul-client = { workspace = true }
lunul-config-program = { workspace = true }
lunul-core = { workspace = true }
lunul-entry = { workspace = true }
lunul-gossip = { workspace = true }
lunul-ledger = { workspace = true }
lunul-logger = { workspace = true }
lunul-pubsub-client = { workspace = true }
lunul-quic-client = { workspace = true }
lunul-rpc-client = { workspace = true }
lunul-rpc-client-api = { workspace = true }
lunul-runtime = { workspace = true }
lunul-sdk = { workspace = true }
lunul-stake-program = { workspace = true }
lunul-streamer = { workspace = true }
lunul-thin-client = { workspace = true }
lunul-tpu-client = { workspace = true }
lunul-turbine = { workspace = true }
lunul-vote = { workspace = true }
lunul-vote-program = { workspace = true }
static_assertions = { workspace = true }
tempfile = { workspace = true }
trees = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
fs_extra = { workspace = true }
gag = { workspace = true }
serial_test = { workspace = true }
lunul-download-utils = { workspace = true }
lunul-ledger = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
