[package]
name = "lunul-sbf-rust-simulation"
description = "Solana SBF Program Simulation Differences"
documentation = "https://docs.rs/lunul-sbf-rust-simulation"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
test-bpf = []

[dependencies]
lunul-program = { workspace = true }

[dev-dependencies]
lunul-logger = { workspace = true }
lunul-program-test = { workspace = true }
lunul-sdk = { workspace = true }
lunul-validator = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
