[package]
name = "lunul-sbf-rust-many-args"
documentation = "https://docs.rs/lunul-sbf-rust-many-args"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
lunul-program = { workspace = true }
lunul-sbf-rust-many-args-dep = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
