[package]
name = "lunul-stake-program"
description = "Solana Stake program"
documentation = "https://docs.rs/lunul-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
lunul-config-program = { workspace = true }
lunul-program-runtime = { workspace = true }
lunul-sdk = { workspace = true }
lunul-vote-program = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
proptest = { workspace = true }
lunul-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "lunul_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
