[package]
name = "lunul-transaction-dos"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
lunul-clap-utils = { workspace = true }
lunul-cli = { workspace = true }
lunul-client = { workspace = true }
lunul-core = { workspace = true }
lunul-faucet = { workspace = true }
lunul-gossip = { workspace = true }
lunul-logger = { workspace = true }
lunul-measure = { workspace = true }
lunul-net-utils = { workspace = true }
lunul-rpc-client = { workspace = true }
lunul-runtime = { workspace = true }
lunul-sdk = { workspace = true }
lunul-streamer = { workspace = true }
lunul-transaction-status = { workspace = true }
lunul-version = { workspace = true }

[dev-dependencies]
lunul-local-cluster = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
