[package]
name = "lunul-thin-client"
description = "Solana Thin Client"
documentation = "https://docs.rs/lunul-thin-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
lunul-connection-cache = { workspace = true }
lunul-rpc-client = { workspace = true }
lunul-rpc-client-api = { workspace = true }
lunul-sdk = { workspace = true }

[dev-dependencies]
lunul-logger = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
