[package]
name = "lunul-validator"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lunul-validator"
default-run = "lunul-validator"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = { workspace = true }
console = { workspace = true }
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
fd-lock = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true, features = ["ipc"] }
jsonrpc-derive = { workspace = true }
jsonrpc-ipc-server = { workspace = true }
lazy_static = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
lunul-accounts-db = { workspace = true }
lunul-clap-utils = { workspace = true }
lunul-cli-config = { workspace = true }
lunul-core = { workspace = true }
lunul-download-utils = { workspace = true }
lunul-entry = { workspace = true }
lunul-faucet = { workspace = true }
lunul-genesis-utils = { workspace = true }
lunul-geyser-plugin-interface = { workspace = true }
lunul-geyser-plugin-manager = { workspace = true }
lunul-gossip = { workspace = true }
lunul-ledger = { workspace = true }
lunul-logger = { workspace = true }
lunul-metrics = { workspace = true }
lunul-net-utils = { workspace = true }
lunul-perf = { workspace = true }
lunul-poh = { workspace = true }
lunul-program-runtime = { workspace = true }
lunul-rayon-threadlimit = { workspace = true }
lunul-rpc = { workspace = true }
lunul-rpc-client = { workspace = true }
lunul-rpc-client-api = { workspace = true }
lunul-runtime = { workspace = true }
lunul-sdk = { workspace = true }
lunul-send-transaction-service = { workspace = true }
lunul-storage-bigtable = { workspace = true }
lunul-streamer = { workspace = true }
lunul-test-validator = { workspace = true }
lunul-tpu-client = { workspace = true }
lunul-unified-scheduler-pool = { workspace = true }
lunul-version = { workspace = true }
lunul-vote-program = { workspace = true }
symlink = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
lunul-account-decoder = { workspace = true }
lunul-runtime = { workspace = true, features = ["dev-context-only-utils"] }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }
signal-hook = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
