[package]
name = "lunul-accounts-bench"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
lunul-accounts-db = { workspace = true, features = ["dev-context-only-utils"] }
lunul-logger = { workspace = true }
lunul-measure = { workspace = true }
lunul-sdk = { workspace = true }
lunul-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
dev-context-only-utils = []
