[package]
name = "lunul-log-analyzer"
description = "The lunul cluster network analysis tool"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
byte-unit = { workspace = true }
clap = { version = "3.1.5", features = ["cargo"] }
serde = { workspace = true }
serde_json = { workspace = true }
lunul-logger = { workspace = true }
lunul-version = { workspace = true }

[[bin]]
name = "lunul-log-analyzer"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
