[package]
name = "lunul-udp-client"
description = "Solana UDP Client"
documentation = "https://docs.rs/lunul-udp-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
lunul-connection-cache = { workspace = true }
lunul-net-utils = { workspace = true }
lunul-sdk = { workspace = true }
lunul-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
