[package]
name = "lunul-unified-scheduler-pool"
description = "The Solana unified scheduler pool"
documentation = "https://docs.rs/lunul-unified-scheduler-pool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
crossbeam-channel = { workspace = true }
derivative = { workspace = true }
log = { workspace = true }
lunul-ledger = { workspace = true }
lunul-program-runtime = { workspace = true }
lunul-runtime = { workspace = true }
lunul-sdk = { workspace = true }
lunul-unified-scheduler-logic = { workspace = true }
lunul-vote = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
lunul-logger = { workspace = true }
lunul-runtime = { workspace = true, features = ["dev-context-only-utils"] }
