[package]
name = "lunul-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lunul-stake-accounts"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
lunul-clap-utils = { workspace = true }
lunul-cli-config = { workspace = true }
lunul-remote-wallet = { workspace = true, features = ["default"] }
lunul-rpc-client = { workspace = true, features = ["default"] }
lunul-rpc-client-api = { workspace = true }
lunul-sdk = { workspace = true }
lunul-stake-program = { workspace = true }
lunul-version = { workspace = true }

[dev-dependencies]
lunul-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
