[package]
name = "lunul-watchtower"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lunul-watchtower"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
humantime = { workspace = true }
log = { workspace = true }
lunul-clap-utils = { workspace = true }
lunul-cli-config = { workspace = true }
lunul-cli-output = { workspace = true }
lunul-logger = { workspace = true }
lunul-metrics = { workspace = true }
lunul-notifier = { workspace = true }
lunul-rpc-client = { workspace = true }
lunul-rpc-client-api = { workspace = true }
lunul-sdk = { workspace = true }
lunul-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
