[package]
name = "lunul-tokens"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/lunul-tokens"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = "2.33.0"
console = { workspace = true }
csv = { workspace = true }
ctrlc = { workspace = true, features = ["termination"] }
indexmap = { workspace = true }
indicatif = { workspace = true }
pickledb = { workspace = true, features = ["yaml"] }
serde = { workspace = true, features = ["derive"] }
lunul-account-decoder = { workspace = true }
lunul-clap-utils = { workspace = true }
lunul-cli-config = { workspace = true }
lunul-remote-wallet = { workspace = true, features = ["default"] }
lunul-rpc-client = { workspace = true, features = ["default"] }
lunul-rpc-client-api = { workspace = true }
lunul-sdk = { workspace = true }
lunul-transaction-status = { workspace = true }
lunul-version = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
lunul-logger = { workspace = true }
lunul-streamer = { workspace = true }
lunul-test-validator = { workspace = true }
