[package]
name = "lunul-quic-client"
description = "Solana Quic Client"
documentation = "https://docs.rs/lunul-quic-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-mutex = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
quinn = { workspace = true }
quinn-proto = { workspace = true }
rustls = { workspace = true, features = ["dangerous_configuration"] }
lunul-connection-cache = { workspace = true }
lunul-measure = { workspace = true }
lunul-metrics = { workspace = true }
lunul-net-utils = { workspace = true }
lunul-rpc-client-api = { workspace = true }
lunul-sdk = { workspace = true }
lunul-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
crossbeam-channel = { workspace = true }
lunul-logger = { workspace = true }
lunul-perf = { workspace = true }
