[package]
name = "lunul-poh-bench"
documentation = "https://docs.rs/lunul-poh-bench"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
log = { workspace = true }
rayon = { workspace = true }
lunul-entry = { workspace = true }
lunul-logger = { workspace = true }
lunul-measure = { workspace = true }
lunul-perf = { workspace = true }
lunul-sdk = { workspace = true }
lunul-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
