# This package only exists to avoid circular dependencies during cargo publish:
# lunul-runtime -> lunul-address-program -> lunul-program-test -> lunul-runtime

[package]
name = "lunul-address-lookup-table-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
lunul-address-lookup-table-program = { workspace = true }
lunul-program-test = { workspace = true }
lunul-sdk = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
