[package]
name = "lunul-test-validator"
description = "Blockchain, Rebuilt for Scale"
readme = "../README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
lunul-accounts-db = { workspace = true }
lunul-cli-output = { workspace = true }
lunul-client = { workspace = true }
lunul-core = { workspace = true }
lunul-geyser-plugin-manager = { workspace = true }
lunul-gossip = { workspace = true }
lunul-ledger = { workspace = true }
lunul-logger = { workspace = true }
lunul-net-utils = { workspace = true }
lunul-program-runtime = { workspace = true }
lunul-program-test = { workspace = true }
lunul-rpc = { workspace = true }
lunul-rpc-client = { workspace = true }
lunul-runtime = { workspace = true }
lunul-sdk = { workspace = true }
lunul-streamer = { workspace = true }
lunul-tpu-client = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
