[package]
name = "lunul-rpc-test"
description = "Solana RPC Test"
documentation = "https://docs.rs/lunul-rpc-test"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
serde = { workspace = true }
serde_json = { workspace = true }
lunul-account-decoder = { workspace = true }
lunul-client = { workspace = true }
lunul-pubsub-client = { workspace = true }
lunul-rpc = { workspace = true }
lunul-rpc-client = { workspace = true }
lunul-rpc-client-api = { workspace = true }
lunul-sdk = { workspace = true }
lunul-streamer = { workspace = true }
lunul-test-validator = { workspace = true }
lunul-tpu-client = { workspace = true }
lunul-transaction-status = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
lunul-logger = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
