[package]
name = "lunul-sbf-rust-mem"
documentation = "https://docs.rs/lunul-sbf-rust-mem"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
no-entrypoint = []
test-bpf = []
dummy-for-ci-check = ["test-bpf"]

[dependencies]
lunul-program = { workspace = true }

[dev-dependencies]
lunul-program-runtime = { workspace = true }
lunul-program-test = { workspace = true }
lunul-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
