[package]
description = "Solana Program Test Framework"
name = "lunul-program-test"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
chrono-humanize = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
lunul-accounts-db = { workspace = true }
lunul-banks-client = { workspace = true }
lunul-banks-interface = { workspace = true }
lunul-banks-server = { workspace = true }
lunul-bpf-loader-program = { workspace = true }
lunul-logger = { workspace = true }
lunul-program-runtime = { workspace = true }
lunul-runtime = { workspace = true }
lunul-sdk = { workspace = true }
lunul-svm = { workspace = true }
lunul-vote-program = { workspace = true }
lunul_rbpf = { workspace = true }
test-case = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
lunul-stake-program = { workspace = true }
