[package]
name = "lunul-send-transaction-service"
description = "Solana send transaction service"
documentation = "https://docs.rs/lunul-send-transaction-service"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
log = { workspace = true }
lunul-client = { workspace = true }
lunul-measure = { workspace = true }
lunul-metrics = { workspace = true }
lunul-runtime = { workspace = true }
lunul-sdk = { workspace = true }
lunul-tpu-client = { workspace = true }

[dev-dependencies]
lunul-logger = { workspace = true }
lunul-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
