[package]
name = "lunul-poh"
description = "Solana PoH"
documentation = "https://docs.rs/lunul-poh"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
lunul-entry = { workspace = true }
lunul-ledger = { workspace = true }
lunul-measure = { workspace = true }
lunul-metrics = { workspace = true }
lunul-runtime = { workspace = true }
lunul-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
rand = { workspace = true }
lunul-logger = { workspace = true }
lunul-perf = { workspace = true }
lunul-poh = { path = ".", features = ["dev-context-only-utils"] }
lunul-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[features]
dev-context-only-utils = []

[lib]
crate-type = ["lib"]
name = "lunul_poh"

[[bench]]
name = "poh"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
